### ISSUE TITLE
Apple Maps poi names still bugged

### ISSUE THREAD

**Issue by Lucasquattro** [OBDb/Audi-RS-3#3]
I’m on last Sidecar release but the POI namas bug is still present
## Cases

| Date confirmed | Date resolved | Model   | Year | Miles   | Owner  | Source  |
|:---------------|:--------------|:--------|:-----|:--------|:-------|:--------|
| 2024-10-28     |   | RS 3 | 2022 | 26514 | @Lucasquattro | [Sidecar](https://sidecar.clutch.engineering) |

**Comment by Lucasquattro** [comment]
Hi! I was not able to upload attachments throught the app, so here it is!

![image](https://github.com/user-attachments/assets/c47c08fe-b74c-4b68-9e4e-6dd7137bffb0)

**Comment by jverkoey** [comment]
Ok I think I've finally isolated this issue to its root cause and have implemented a fix that should resolve this for the next release :D
